import localFont from "next/font/local";
import "./style/globals.css";

// Fustat
const fustat = localFont({
  src: [
    {
      path: "./fonts/Fustat/static/Fustat-Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/Fustat/static/Fustat-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/Fustat/static/Fustat-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
  ],
  variable: "--font-fustat",
  display: "swap",
});

// Helvetica Now
const helveticaNow = localFont({
  src: "./fonts/helvetica-now-display/HelveticaNowDisplay-Regular.ttf",
  variable: "--font-helvetica-now",
  display: "swap",
});

// Segoe UI
const segoeUi = localFont({
  variable: "--font-segoeUi",
  display: "swap",
  src: [
    {
      path: "./fonts/segoe-ui-this/Segoe UI Regular.ttf",
      weight: "400",
      style: "regular",
    },
    {
      path: "./fonts/segoe-ui-this/3868-font.ttf",
      weight: "600",
      style: "semibold",
    },
  ],
});

// The Bold Font
const theBoldFont = localFont({
  variable: "--font-the-bold",
  display: "swap",
  src: [
    {
      path: "./fonts/the_bold_font/THEBOLDFONT-FREEVERSION.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fustat.variable} ${helveticaNow.variable} ${segoeUi.variable} ${theBoldFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}