import { Fustat } from "next/font/google";
import localFont from "next/font/local";
import "./style/globals.css";

const fustate = Fustat({
  variable: "--font-fustate",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const HelveticaNowDisplay = localFont({
  variable: "--font-Helvetica-Now-Display",
  display: "swap",
  src: [
    {
      path: "../../public/fonts/helvetica-now-display/HelveticaNowDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const segoeUi = localFont({
  variable: "--font-segoeUi",
  display: "swap",
  src: [
    {
      path: "../../public/fonts/segoe-ui-this/segoeuithis.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const theBoldFont = localFont({
  variable: "--font-the-bold",
  display: "swap",
  src: [
    {
      path: "../../public/fonts/the_bold_font/THEBOLDFONT-FREEVERSION.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fustate.variable} ${HelveticaNowDisplay.variable} ${segoeUi.variable} ${theBoldFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
